### ISSUE TITLE
Read youtube plugin settings

### ISSUE THREAD

**Issue by Tolriq** [Tolriq/repository.yatse.kodi#12]
Is there a way to read another addon settings?

Typically I'd like to read the youtube setting use MPEG-DASH to then use the youtube plugin directly and not youtube dl without adding an option inside Yatse plugin.

Ping @Nemiroff

**Comment by Nemiroff** [comment]
`youtube_addon = xbmcaddon.Addon(id="plugin.video.youtube")
    if youtube_addon:
        if yotube_addon.getSetting("kodion.video.quality.mpd")" == "true":`

**Comment by Tolriq** [comment]
Nice thanks a lot.
