### ISSUE TITLE
Status notifications

### ISSUE THREAD

**Issue by quthla** [Tolriq/repository.yatse.kodi#14]
Can you maybe add some notifications? [This](https://github.com/firsttris/plugin.video.sendtokodi) addon has it and it's quite helpful to know what's going on.

**Comment by Tolriq** [comment]
Not sure to understand? Yatse did show a busy dialog but Kodi 18 broke that :)

What do you expect when where?

**Comment by quthla** [comment]
Something like this. It's working fine in Kodi 18

https://github.com/firsttris/plugin.video.sendtokodi/blob/master/service.py#L89
https://github.com/firsttris/plugin.video.sendtokodi/blob/master/service.py#L103

**Comment by Tolriq** [comment]
Ho real notifications :( The problem with those is that I did not found a way to close them and you need to pass arbitrary duration on call.

So if the addon takes 1sec to resolve you still have the notification for X seconds over the video playing :( I did not like that when I tested when creating the addon.

**Comment by quthla** [comment]
I am used to them from the other addon and personally I don't have any issue with that. With your addon it works but I'm never sure what exactly is happening or if it even received the url from the app.

**Comment by Tolriq** [comment]
Next version will use notifications with short display duration. Can you please test with the source here and confirm?

**Comment by quthla** [comment]
There's still a notification missing for when the unresolved url is received from the app? 

And about the closing problem: maybe you can clear the notification by displaying another notification for like 10ms. But honestly I doubt anybody feels disturbed by a 5s or in your case 3s notification

**Comment by Tolriq** [comment]
There's a notification showing as soon as resolving start saying resolving media. What more do you want?

**Comment by quthla** [comment]
Okay my bad. Must've overlooked it. I guess it'll work then. Can you release it?

**Comment by Tolriq** [comment]
Not yet I have more tests to do with dash support.

But you can still use it from source ;)

**Comment by Tolriq** [comment]
Released in version 1.6.0
