### ISSUE TITLE
Queuing youtube videos no longer works with mpd enabled in plugin

### ISSUE THREAD

**Issue by iamsix** [Tolriq/repository.yatse.kodi#15]
The new method of playing youtube with mpd support is nice, but sharing a youtube with "Queue on media center" no longer queues them in the playlist - it immediately plays and clobbers the playlist.

Another oddity with playing through the plugin - the first time you play a youtube (never played before) the yatse interface doesn't know that subtitles are there to be enabled/disabled (the OSD within kodi does), and the 'audio options' within the remote isn't there - if you re-play the same youtube it works normally.

**Comment by Tolriq** [comment]
As always https://yatse.tv/wiki/debug-yatse-kodi-remote log for the seconds part :)

For the first part I'll see how I can fix it.

**Comment by Tolriq** [comment]
1.6.1 released for point 1.

**Comment by iamsix** [comment]
New version is working good with queuing on my tests so far, and curiously seems to have completely fixed the second part as well.

**Comment by Tolriq** [comment]
Well then it's a bug with Json in Kodi 18 when starting the addon :( One more nice touch of v18 :)
