### ISSUE TITLE
Handle Kodi 19 decision that force to maintain 2 repository and 2 identical addons...

### ISSUE THREAD

**Issue by Tolriq** [Tolriq/repository.yatse.kodi#18]
@Nemiroff Since you manage repo and addons do you have any idea about how to handle that properly?

https://github.com/xbmc/xbmc/issues/17326
https://forum.kodi.tv/showthread.php?tid=351745

**Comment by Nemiroff** [comment]
I try not to bother yet, as there is no stable version of Matrix yet.

**Comment by Tolriq** [comment]
Ok :( According to the kodi issue in the coming weeks addons won't load anymore on matrix will at least need a way to explain that to users of the alphas :'(

**Comment by Tolriq** [comment]
Since they merged and broke addons I searched a little more and it seems you can have multiple directories inside a single repository with Kodi version "handling"

```
	<extension point="xbmc.addon.repository" name="Yatse Kodi Add-on repository">
		<dir minversion="14.0.0">
			<info compressed="false">https://raw.githubusercontent.com/Tolriq/repository.yatse.kodi/master/zips/addons.xml</info>
			<checksum>https://raw.githubusercontent.com/Tolriq/repository.yatse.kodi/master/zips/addons.xml.md5</checksum>
			<datadir zip="true">https://raw.githubusercontent.com/Tolriq/repository.yatse.kodi/master/zips/</datadir>
			<hashes>false</hashes>
		</dir>
		<dir minversion="18.9.0">
			<info compressed="false">https://raw.githubusercontent.com/Tolriq/repository.yatse.kodi/master/matrix/addons.xml</info>
			<checksum>https://raw.githubusercontent.com/Tolriq/repository.yatse.kodi/master/matrix/addons.xml.md5</checksum>
			<datadir zip="true">https://raw.githubusercontent.com/Tolriq/repository.yatse.kodi/master/matrix/</datadir>
			<hashes>false</hashes>
		</dir>
	</extension>
```

Coupled with an ugly script that change version + name + python version to generate the matrix version without effort seems to works. Matrix addon generator should be improved but I hate python :p
