### ISSUE TITLE
Option to disable resolving YouTube links

### ISSUE THREAD

**Issue by siku2** [Tolriq/repository.yatse.kodi#19]
When sharing a video with Yatse the helper script takes precedence over the YouTube add-on and ends up playing the direct link to the video file.
This is a problem for add-ons that rely on the YouTube add-on such as [SponsorBlock](https://github.com/siku2/script.service.sponsorblock) because it leaves them unable to detect the video id.

How about adding an option to disable the behavior which defaults to true when the YouTube add-on is installed?

I am aware that the script already uses the YouTube add-on but that's only when the setting to "Use MPEG-DASH" is enabled.

**Comment by Tolriq** [comment]
Why don't enable that option then ? :)

Even if I do add the option at some point it won't be default for sure since the addon was made to allow sharing proper meta data for playlist and a few other things that does not work without it.

Not talking about the issues with the addon currently for many users.

**Comment by siku2** [comment]
I get your point but I really don't think that telling the average user to enable some obscure option in the YouTube add-on settings is a good idea.

I admit, me saying that the option should be enabled by default was a bit naive, but I still think that it should at least exist.

> the addon was made to allow sharing proper meta data for playlist and a few other things that does not work without it

Can I ask you to elaborate on this a bit, perhaps this is something we can upstream into the YouTube add-on.

Speaking of which, an upcoming release of the add-on should fix the API key issue when videos are being played directly.

I'm totally willing to make the changes myself and open a pull request but I wanted to discuss this first.

**Comment by siku2** [comment]
See, the real problem is that when you play YouTube videos using the media url from googlevideo.com it doesn't contain the video id anymore and to my knowledge it's impossible to look it up either.

Another way to solve this would be to use a plugin url like the YouTube add-on does which could then contain the video id in it. That would take longer to implement though.

Yet another solution might be to send a [JSON-RPC notfication](https://kodi.wiki/view/JSON-RPC_API/#JSONRPC.NotifyAll) containing the meta data before playing a video.

**Comment by Tolriq** [comment]
When Yatse resolve the media the metadata is added. What do you need where? 

And for the record Yatse works without this addon and use the Kodi addon.

And asking user to change a setting in Yatse or in Youtube is pretty much the same.

To finish Kodi API does not allow pushing metadata from JSON so when you queue youtube addon url the playlist only show a list of play?id that is not usable.

**Comment by siku2** [comment]
Thanks for explaining. If I understand correctly the issue is that sharing a YouTube URL normally doesn't add any metadata to the `ListItem` which is indeed rather unfortunate.


> And asking user to change a setting in Yatse or in YouTube is pretty much the same.

I totally agree but that's not what I take issue with. I think it's problematic that it's not obvious that enabling "Use MPEG-DASH" does this. If I hadn't looked at the source code I wouldn't have known.

What if a user doesn't want to use adaptive streaming but still wants to use the YouTube add-on?
There are many reasons why one would want to play the videos with the add-on. Most notably, tracking your watch history.

I really don't understand why you're pushing back so hard...

**Comment by Tolriq** [comment]
As I said this addon is optional Yatse can share youtube without it and it does use the Kodi addon as you need.

There's also a way to do that via the Youtube addon option.

The question is more why are you pushing so hard on this need that no one asked before?

This addon only exists because I can't fix Kodi core and can't even publish there due to some ... ;) Even if such feature would benefit all users.

I hate python this is a pain to maintain (Hello stupid choices for Kodi 19 ...)
So sorry but I won't add support burden for things I don't see fitting right now.

At contrario I got a few bad ratings and insults from users who did not use this addon and add the share function broken due to Kodi addon issue.

**Comment by siku2** [comment]
Alright, I understand there's no point in pursuing this any further. I'm sorry you're having such a bad time maintaining this add-on. I would offer my help but it doesn't seem like you'd accept.

Thank you for taking your time to respond to this issue.

**Comment by Tolriq** [comment]
Well you are ignoring the truth here ;)

As said:
When Yatse resolve the media the metadata is added. What do you need where?

Instead of drawing false conclusions you may want to read more and understand that what YOU think is the solution to your issue is maybe not the only solution or even the best.

From your addon code you could support Yatse with just looking at the data in another way ;) 
But yes I'm the bad guy who try to see big picture and not blindly do things ;)

**Comment by siku2** [comment]
I'm sorry if it came off as me trying to paint you as "the bad guy", that wasn't my intention at all.

I still intend on adding support for the helper script. Either by using the URL metadata or if that doesn't work extracting the video id from the thumbnail URL.

The reason I closed this issue is because it's specifically about adding an option to always use the YouTube add-on for YouTube videos and you explicitly stated that you do not want that.

**Comment by Tolriq** [comment]
The only certainty is that it would not be default.

I then tried to gather the need to find proper solution and you told me I was pushing back when I tried to move forward :)

Anyway as said Yatse push metadata so you can query Kodi active media details and get many info. I can add the json or the id anywhere hence the question about what you need that is still not answered.

**Comment by siku2** [comment]
Okay I see where I went wrong. That was a badly thought out statement on my part, I have misjudged your intentions.

Anyway, all I need is the video id but I'm not sure whether it makes sense to include it separately because I should be able to easily extract it from the url or thumbnail url.

**Comment by Tolriq** [comment]
As you want but I can add anything youtube dl returns as listtitem property that you can get easily

**Comment by siku2** [comment]
If it's not too much to ask for then by all means, please add it. I'll still use the other properties as a fallback for the foreseeable future because of backward compatibility.

**Comment by Tolriq** [comment]
So took me a few hours of work and 10000 lines of codes but if you get Kodi current player active listItem and it's a youtube video resolved by this plugin it will have a property 'youtubeId' that will contain the youtube ID.

It's not yet published so copy the file manually to test, report if it works for you and I'll make a public update after. Already to many updates to support Kodi 19 without maintaining 2 addon.

**Comment by siku2** [comment]
Perhaps I'm overlooking something here but I haven't found a way to get access to the custom properties you're adding to the `ListItem`.

Things I've tried:
- `getInfoLabel` to get "ListItem.Property(videoId)" doesn't return anything. In fact the "ListItem" info labels seems to be set at all.
- `Player.getVideoInfoTag()` returns a [InfoTagVideo](https://codedocs.xyz/AlwinEsch/kodi/group__python___info_tag_video.html) which only seems to provide a subset of the `ListItem` properties and from looking at the [source code](https://github.com/xbmc/xbmc/blob/3236f461d9978a1cdbd7122c2d3004da38f87edb/xbmc/video/VideoInfoTag.h) it doesn't look like it even cares about custom properties.
- The JSON RPC [Player.GetItem](https://kodi.wiki/view/JSON-RPC_API/v8#Player.GetItem) method makes sure that the key you ask for matches against an enum so no way of getting custom properties there. Same for the [Player.GetProperty](https://kodi.wiki/view/JSON-RPC_API/v8#Player.GetProperties) method.

So *naturally* I decided to spend 2 hours of my life searching through the source code of Kodi and from what I can tell the only time anything from the `GUIInfoManager` (which is what seems to be storing the metadata) is exposed to the Python interface is for the `getVideoInfoTag` and `getMusicInfoTag`. As previously mentioned these don't appear to expose the custom properties.

If you know more about this I would really appreciate you sharing it with me.

For now I decided to use the thumbnail url strategy I mentioned before. I can get the thumbnail url using the JSON RPC and it seems to be working reliably.

**Comment by Tolriq** [comment]
Well it seems Kodi python is even more stupid than I thought, seeing all the add and other stuff from Playlist I supposed they had a get, but no why propose a simple function ....

I told you maintaining Kodi addons is a pain there's no logic anywhere in any taken decision and different behaviors for the same action depending on the path / API used .... 

Anyway for Kodi 18 the id is now added as a uniqueID with name youtubeID for videos.

Can't do more for pre Kodi18 version without possible side effects, only other solution would be that I add a YoutubeID:XXXXX in the end of the description that you could regexp.

**Comment by siku2** [comment]
This is way too cursed for my little heart. First it turns out that I can only get these properties with the JSON RPC. Fine, I guess, I can live with that. But then I have to find out `Player.GetItem` doesn't return the "uniqueid" field because of course it doesn't, how dare I even think it would.
Apparently you have to use the `Playlist.GetItems` method which does, for some reason, return the uniqueid field. But now I need to use a second call to determine the current playlist index because there's no way to only return the current item. Oh wait, that would be `Player.GetItem` wouldn't it?

I have to agree with you that the Kodi Python interface is laughable at best.

I think at this point I have to throw in the towel and call the thumbnail method "good enough". 
The upside is that this method *should* be more generally applicable.
Adding it to the description isn't necessary. It would only detract from the user experience.

**Comment by Tolriq** [comment]
Load really the python VideoTags does not expose it? There's really a problem on how Kodi is maintained they keep adding stuff half baked ignoring python or Json ....

I then hope the thumbnail solution works, Kodi is a mess :'(
