### ISSUE TITLE
Yatse android does not know how to work on vpn which is configured on the system where kodi is running.

### ISSUE THREAD

**Issue by lavaed** [Tolriq/repository.yatse.kodi#25]
I understand that this is not a problem in adon, but I hope that here they help me with this problem. Kodi is installed on a system with a vpn server and I sometimes need yatse android running via vpn connected to the server with Kodi running.
When sending file from yatse android app to kodi with vpn connected. Yatse sends the wrong ip of the android device on which yatse is installed.
    
    172.16.0.20.49559 > 172.16.0.1.8080: Flags [P.], cksum 0xd636 (correct), seq 11421:12250, ack 11312, win 432, options 
    [nop,nop,TS val 12291460 ecr 1698060520], length 829: HTTP, length: 829
	POST /jsonrpc HTTP/1.1
	Content-Type: application/json; charset=utf-8
	Content-Length: 639
	Host: 172.16.0.1:8080
	Connection: Keep-Alive
	Accept-Encoding: gzip
	User-Agent: okhttp/4.9.1
	
    {"id":253,"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"params":{"mime_type":"image/jpeg","thumbnail":"http%3A%2F%2F10.5.75.222%3A46178%2FC4A81F353271D807D5A7E076B8012C70%2F%252Fstorage%252FABDB-62E7%252FDCIM%252Fimage%252F%25D0%25A0%25D0%25B0%25D0%25B1%25D0%25BE%25D1%2582%25D0%25B0%252FDSCF1758.JPG%23FromYatse","title":"DSCF1758.JPG","play_action":"play","action":"stream","data":"http%3A%2F%2F10.5.75.222%3A46178%2FC4A81F353271D807D5A7E076B8012C70%2F%252Fstorage%252FABDB-62E7%252FDCIM%252Fimage%252F%25D0%25A0%25D0%25B0%25D0%25B1%25D0%25BE%25D1%2582%25D0%25B0%252FDSCF1758.JPG%23FromYatse"},"addonid":"script.yatse.kodi"}}[!http]
  I took this log from tcpdump.
 Kodi writes the following in its logs.

    2021-03-14 14:59:31.072 T:140192665024256  NOTICE: ES: Client  from ::ffff:172.16.0.20 timed out
    2021-03-14 15:04:01.344 T:140194560833280   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for 
    http://10.5.75.222:47403/C4A81F353271D807D5A7E076B8012C70/%2Fstorage%2FABDB- 
    62E7%2FDCIM%2Fimage%2F%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%2FDSCF1758.JPG#FromYatse
    2021-03-14 15:04:31.378 T:140194560833280   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
    2021-03-14 15:04:31.378 T:140194560833280   ERROR: CCurlFile::Open failed with code 0 for 
    http://10.5.75.222:47403/C4A81F353271D807D5A7E076B8012C70/%2Fstorage%2FABDB- 
    62E7%2FDCIM%2Fimage%2F%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%2FDSCF1758.JPG#FromYatse:

Is it possible to fix yatse android so that it can work with vpn?

**Comment by Tolriq** [comment]
This is not the proper place. 

See https://yatse.tv/wiki/debug-yatse-kodi-remote to open issue with proper logs.
