### ISSUE TITLE
Youtube links not working

### ISSUE THREAD

**Issue by FunctionalHacker** [Tolriq/repository.yatse.kodi#31]
If I have the Yatse helper script installed, I am unable to play Youtube videos. This is regardless of the plugin setting 'Prefer Kodi Youtube addon for Youtube urls'.

Once I disable the script addon, I am able to share Youtube videos again. With the addon enabled, links beside Youtube work.

**Comment by Tolriq** [comment]
Please provide the necessary logs from Kodi with the debug mode enabled in the addon.

**Comment by Tolriq** [comment]
Or don't but there's 99% chance this is a Kodi plugin issue https://github.com/anxdpanic/plugin.video.youtube/issues/274 either not released or the fix still not enough....

**Comment by FunctionalHacker** [comment]
Sorry I was going to get you the logs but I was busy. Sure looks like the bug above might be the cause, thanks.
