### ISSUE TITLE
[Feature request] YATP Support

### ISSUE THREAD

**Issue by martinrevert** [Tolriq/repository.yatse.kodi#5]
Any future chance to support YATP as an option to send magnets links?

https://github.com/romanvm/kodi.yatp

thanks!

**EDIT:**
Sorry, cannot pull request from this machine, but as per https://github.com/romanvm/kodi.yatp/wiki/Kodi-Plugin-API seems that the only need is to add this to the magnet selection:

```
	elif openWith == 'YATP':
            utils.callPlugin('plugin://plugin.video.yatp/?action=play&torrent=' + argument['data'] + ')')
```

**Comment by Tolriq** [comment]
Well ask the Author addon the actual command to play the magnet links and I can yes.

**Comment by martinrevert** [comment]
Ups, crossposted with my edit. See above. thanks again.

**Comment by Nemiroff** [comment]
For one file torrent its work. But if torrent is multifile (tv shows full season) need send more data.

**Comment by Tolriq** [comment]
In all cases as it's shared from a website or another app Yatse won't have the necessary extra data. So I'll add support with default option that play the biggest file as I can't really do more. 
And the addon was made to add support to such other addons.

**Comment by Tolriq** [comment]
Well I do not use those plugins just tell me what's better and I'll push with that all is ready prepared was going to push with initial proposal.

**Comment by Tolriq** [comment]
I've pushed with the file_index=dialog as from the doc seems the best.
Won't be too much available today and wanted your other fix to be pushed.
Feel free to reopen if it does not work.
