### ISSUE TITLE
Find a workaround for Kodi 18 bug

### ISSUE THREAD

**Issue by Tolriq** [Tolriq/repository.yatse.kodi#8]
Writing here in case someone have an idea  :)

Kodi 18 have a bug that prevent playing video url that contains a ? in the url. (And since I'm banned from everywhere for saying that there's no more JSON maintainer I can't officially report to Team Kodi)
Since the Yatse plugin was started, plan was to use the plugin to overcome the limitation.

But the bug also affect Python addons in a certain way: 
- ```list_item.setInfo('video', item_info)``` will not properly work if the list_item path contains a ?

And after JSON will return wrong file value without the ? and the arguments and no meta data.

Easy to test with Yatse plugin 1.3.0 on a recent Kodi 18. Just share a youtube video that have a description and see the result.

So the question is does anyone have an idea about to bypass / workaround this bug? (That was most probably created by Koying when changing parameters handling (he his aware) but since he's no more around I doubt a fix will be made).

**Comment by luispabon** [comment]
What if you escape the string before sending off to kodi for playback? Single or double quoting might also help?

**Comment by Tolriq** [comment]
This is more complex than that ;) All worked perfectly before a change internal to Kodi that decided to split on ? when coming from certain path.
If I encode then the param are no more params and the url does not work :)
Let's hope someone fix that before v18 is beta / final.
